baseURL: http://budavariam.github.io/
languageCode: en-us
title: Mátyás Budavári
description: Developer from Szeged
theme: "PaperModBudavariam"
paginate: 20

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-115499513-1

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    author: Mátyás Budavári
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: true
    hidemeta: false
    showtoc: true
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Mátyás Budavári"
        icon: /avatar.png
        iconHeight: 70

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: gmail
          value: budavariam@gmail.com
        - name: github
          value: budavariam
        - name: gitlab
          value: budavariam
        - name: linkedin
          value: budavariam
        - name: codefights
          value: budavariam
        - name: stackoverflow
          value: users/9174012/mátyás-budavári
        # - name: rss
        #   value: + # just type anything here for a working RSS icon
        - name: strava
          value: 65326224
        - name: duolingo
          value: budavariam
        - name: instagram
          value: budavariam
        - name: twitter
          value: budavari
        - name: tumblr
          value: budavari
        - name: facebook
          value: budavariam
        # - name: dribbble
        #   value:
        # - name: email
        #   value:
        # - name: flickr
        #   value:
        # - name: pinterest
        #   value:
        # - name: youtube
        #   value: # channel/<your_long_string> or user/<user-name>
        # - name: googleplus
        #   value: # anything in your profile username that comes after plus.google.com/

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: about
          name: about
          url: /about/
          weight: 10
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai






# name: Mátyás Budavári
# description: Developer from Szeged
# avatar: https://avatars2.githubusercontent.com/u/33528704?s=460&v=4


# # Enter your Disqus shortname (not your username) to enable commenting on posts
# # You can find your shortname on the Settings page of your Disqus account
# disqus: budavariam

# # Enter your AddThis script url
# addthisurl: //s7.addthis.com/js/300/addthis_widget.js#pubid=ra-602c2f70bcebfd93

# # Enter your Google Analytics web tracking code (e.g. UA-1234567-8) to activate tracking
# google_analytics: UA-115499513-1

# url:

# baseurl: ""

# #

# permalink: posts/:year/:month/:day/:title/

# # Jekyll 3 now only supports Kramdown for Markdown
# kramdown:
#   # Use GitHub flavored markdown, including triple backtick fenced code blocks
#   input: GFM
#   # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     # Use existing pygments syntax highlighting css
#     css_class: 'highlight'

# # Set the Sass partials directory, as we're using @imports
# sass:
#   style: :expanded # You might prefer to minify using :compressed

# # Use the following plug-ins
# plugins:
#   - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#   - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# # Exclude these files from your production _site
# exclude:
#   - docker/
#   - docker-compose.yml
#   - Gemfile
#   - Gemfile.lock
#   - LICENSE
#   - README.md
#   - CNAME
#   - utils/
#   - images/svg-icons/

# defaults:
#   - scope:
#       path: "assets/food"
#     values:
#       food: true
#   - scope:
#       path: "_posts"
#     values:
#       comments: true
#       language: en