baseURL: http://budavariam.github.io/
languageCode: en-us
title: Mátyás Budavári
description: Developer from Szeged
theme: "PaperModBudavariam"
paginate: 20

enableRobotsTXT: true
enableInlineShortcodes: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqusShortname: budavariam

# Enter your AddThis script url

googleAnalytics: UA-115499513-1

permalinks: 
  posts: "/posts/:year/:month/:day/:title/"

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    author: Mátyás Budavári
    images: ["<link or path of image for opengraph, twitter-cards>"]
    addthisurl: "//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-602c2f70bcebfd93"

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: true
    hidemeta: false
    showtoc: true
    tocopen: false
    searchHidden: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: /favicon/favicon.ico
        favicon16x16: /favicon/favicon-16x16.png
        favicon32x32: /favicon/favicon-32x32.png
        apple_touch_icon: /favicon/apple-icon-180x180.png
        safari_pinned_tab: /favicon/apple-icon-180x180.png

    label:
        text: "Mátyás Budavári"
        icon: /avatar.png
        iconHeight: 70
        iconWidth: 70

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: /avatar.png
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: I like to post about the tools I use, and the productivity hacks I come across. I hope you'll enjoy my content.

    socialIcons:
        - name: gmail
          value: budavariam@gmail.com
        - name: github
          value: budavariam
        - name: gitlab
          value: budavariam
        - name: linkedin
          value: budavariam
        - name: codefights
          value: budavariam
        - name: stackoverflow
          value: users/9174012/mátyás-budavári
        - name: rss
          value: ""
        - name: strava
          value: 65326224
        - name: duolingo
          value: budavariam
        - name: instagram
          value: budavariam
        - name: twitter
          value: budavari
        - name: tumblr
          value: budavari
        - name: facebook
          value: budavariam
        # - name: dribbble
        #   value:
        # - name: email
        #   value:
        # - name: flickr
        #   value:
        # - name: pinterest
        #   value:
        # - name: youtube
        #   value: # channel/<your_long_string> or user/<user-name>
        # - name: googleplus
        #   value: # anything in your profile username that comes after plus.google.com/

    analytics:
        google:
            SiteVerificationTag: "ocrG4G5ZSn2awC0mgHAsgk2qlhd3IAXCACgWNrqJcwY"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page
        relative: false

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 10
        - identifier: archives
          name: Archive
          url: /archives/
        - identifier: about
          name: About
          url: /about/
          weight: 10
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary